name: Trigger Config Repo Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  trigger-repo-config:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo B Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}  
          repository: xDarkN/TaskM_Config  
          event-type: trigger-config    